### ISSUE TITLE
UnboundLocalError: local variable 'error_data' referenced before assignment

### ISSUE THREAD

**Issue by kidynamit** [rehive/rehive-python#72]
```Traceback (most recent call last):
  File "/Users/mwangi/.pyenv/versions/gatling/lib/python3.7/site-packages/rehive/api/client.py", line 118, in _request
    error_data = result.json()
  File "/Users/mwangi/.pyenv/versions/gatling/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/mwangi/.pyenv/versions/3.7.4/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/mwangi/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/mwangi/.pyenv/versions/3.7.4/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/setup_testing_company.py", line 153, in <module>
    credit_test_users()
  File "src/setup_testing_company.py", line 139, in credit_test_users
    credit_user(user.identifier)
  File "src/setup_testing_company.py", line 133, in credit_user
    amount=1000000, currency="USD", status="Complete", user=identifier)
  File "/Users/mwangi/.pyenv/versions/gatling/lib/python3.7/site-packages/rehive/api/resources/admin_resources.py", line 188, in create_credit
    response = self.post(data, 'credit/', **kwargs)
  File "/Users/mwangi/.pyenv/versions/gatling/lib/python3.7/site-packages/rehive/api/resources/base_resources.py", line 44, in post
    **request_kwargs
  File "/Users/mwangi/.pyenv/versions/gatling/lib/python3.7/site-packages/rehive/api/client.py", line 51, in post
    return self._request('post', path, data, json=json, **kwargs)
  File "/Users/mwangi/.pyenv/versions/gatling/lib/python3.7/site-packages/rehive/api/client.py", line 123, in _request
    APIException(error_data.get(
UnboundLocalError: local variable 'error_data' referenced before assignment```

**Comment by OdinsPlasmaRifle** [comment]
This errors occurs when the API does not return the expected JSON response (for if there is a issue in the ingress or some sort of server error occurs). Can you please modify the code on this line:

https://github.com/rehive/rehive-python/blob/master/rehive/api/client.py#L132

To not reference `error_data` and instead just throw an `APIException` saying `JSON Decode error` (and including the status code).
